/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tym6.sachy;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Panel;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import javax.swing.JPanel;

/**
 *
 * @author Valecek, Maca, Beran, Pavlik
 */
public class Okno extends javax.swing.JFrame {
    Boolean prvniSpusteni = true;
    int velikost = 100;
    int posunX = 25;
    int posunY = 25;
    Hlavni hlavni;
    /**
     * Creates new form Okno
     */
    public Okno() {
        initComponents();
        addMouseListener(new MysListener());
        hlavni = new Hlavni();
    }
    public BufferedImage hraciDeska(){
        BufferedImage bfi = new BufferedImage(850, 850, BufferedImage.TYPE_INT_ARGB);
        Graphics2D gr = bfi.createGraphics();
        
        
        
        char znaky[] = {'a','b','c','d','e','f','g','h'};
        for(int i=0; i<8; i++){
            gr.setColor(Color.blue);
            gr.setFont(new Font("Serif", Font.BOLD, 20));
            gr.drawString(znaky[i]+"", velikost/2+posunX+i*velikost-2, 18);
            for(int j=0; j<8; j++){
                gr.setColor(Color.blue);
            gr.setFont(new Font("Serif", Font.BOLD, 20));
            gr.drawString(8-i+"", 5, velikost/2+posunY+i*velikost+5);
                if(i%2==0){
                    if(j%2==0){
                        gr.setColor(Color.LIGHT_GRAY);
                        gr.fill(new Rectangle(posunX+j*velikost, posunY+i*velikost, velikost, velikost));
                    }else{
                        gr.setColor(Color.DARK_GRAY);
                        gr.fill(new Rectangle(posunX+j*velikost, posunY+i*velikost, velikost, velikost));
                    }
                }else{
                    if(j%2==0){
                        gr.setColor(Color.DARK_GRAY);
                        gr.fill(new Rectangle(posunX+j*velikost, posunY+i*velikost, velikost, velikost));
                    }else{
                        gr.setColor(Color.LIGHT_GRAY);
                        gr.fill(new Rectangle(posunX+j*velikost, posunY+i*velikost, velikost, velikost));
                    }
                }
            }
        }
        
        return bfi;
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g); 
        if(prvniSpusteni ==  true){
            jPanel1.getGraphics().drawImage(hraciDeska(), 0, 0, null);
            prvniSpusteni = false;
        }
    }
    
    public int []najdiSouradniceCtverce(int x, int y){
        int pole[] = new int[2]; 
        for(int i=0; i<8; i++){
            for(int j=0; j<8; j++){
                if(x>=j*velikost+posunX&&x<=j*velikost+posunX+velikost&&y>=i*velikost+posunY+this.getInsets().top&&y<=i*velikost+posunY+this.getInsets().top+velikost){
                    //System.out.println("souradnice: "+pole[0]+" i"+i+" "+" y"+y+" "+pole[1]);
                    pole[0] = j*velikost+posunX;
                    pole[1] = i*velikost+posunY;
                    BufferedImage bfi = new BufferedImage(850, 850, BufferedImage.TYPE_INT_ARGB);
                    Graphics2D gr = bfi.createGraphics();
                    gr.setColor(Color.YELLOW);
                    float opacity = 0.5f;
                    gr.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, opacity));
                    gr.fill(new Rectangle(pole[0], pole[1], velikost, velikost));
                    jPanel1.getGraphics().drawImage(bfi, 0, 0, null);
                }
            }
        }
         
        return pole;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(3276, 3276));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(455, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jPanel1.getGraphics().drawImage(hraciDeska(), 0, 0, null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
private class MysListener extends MouseAdapter{
    @Override
    public void mouseClicked(MouseEvent event){
        int x = event.getX();
        int y = event.getY();
        System.out.println("asdfůa");
        najdiSouradniceCtverce(x, y);
    }
}

}

